name: CI Build Testing
on:
  push:
    branches: [ master ]
    paths-ignore:
      - Jenkinsfile
      - Readme.md
      - pom.xml
  workflow_dispatch:

jobs:
  builds:
    name: build
    runs-on: ubuntu-latest
	  if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    steps:
    - name: Checkout
      uses: actions/checkout@master  
    - name: folder_change
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          server:
            - 'server/**'
          webapp:
            - 'webapp/**'
    - name: server_tests
      if: steps.filter.outputs.server == 'true'
      run: |
            cd server
            cat Dockerfile

    - name: webapp_tests
      if: steps.filter.outputs.webapp == 'true'
      run: |
            cd server
            cat Dockerfile

