name: CI Build Testing
on:
  push:
    branches: [ master ]
    paths-ignore:
      - Jenkinsfile
      - Readme.md
      - pom.xml
  workflow_dispatch:

jobs:
  server:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
          - 'server/**'
    - name: dockerfile_display
      if: steps.changes.outputs.src == 'true'
      run: |
            cd server
             cat Dockerfile
    
  webapp:
    name: webapp
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
          - 'webapp/**'
    - name: dockerfile_display
      if: steps.changes.outputs.src == 'true'
      run: |
            cd webapp
            cat Dockerfile

  

