name: CI Build Testing
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: AWS ECR
      uses: kciter/aws-ecr-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: 549450938468
        repo: myrepo
        region: us-east-2
        dockerfile: Dockerfile
        tags: $GITHUB_RUN_NUMBER
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: myfunction
        dry_run: true

