name: CI Build Testing
on:
  push:
    branches: [ master ]
    paths-ignore:
      - Jenkinsfile
      - Readme.md
      - pom.xml
  workflow_dispatch:
jobs:
  build:
    name: AWS ECR login
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          server:
            - 'server/**'
          webapp:
            - 'webapp/**'
    - name: server
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: myrepo/server
        IMAGE_TAG: ${{ github.run_number }}
      if: steps.filter.outputs.server == 'true'
      run: |
            cd server
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            aws lambda update-function-code --region us-east-2 --function-name my-function --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: webapp
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: myrepo/webapp
        IMAGE_TAG: ${{ github.run_number }}
      if: steps.filter.outputs.webapp == 'true'
      run: |
            cd server
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            aws lambda update-function-code --region us-east-2 --function-name myfunction --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

