name: CI Build Testing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Linting and Static Analysis
      run: |
        # Install hadolint
        DOWNLOAD_URL="https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64"
        LOCAL_FILE=./hadolint
        curl -Lo $LOCAL_FILE $DOWNLOAD_URL
        chmod +x $LOCAL_FILE
        sudo mv $LOCAL_FILE /usr/local/bin
        # lint Dockerfile with exceptions(example)
        hadolint --ignore DL3018 --ignore DL3007 $(find . -name 'Dockerfile')
    - name: Set Build Info
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        export BUILD_NAME="${GITHUB_REPOSITORY//[\/]/-}"
        BUILD_NAME+="-master"
        echo "$BUILD_NAME"
        export BUILD_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_NUMBER"
        echo ::set-env name=JFROG_CLI_BUILD_NAME::$(echo $BUILD_NAME)
        echo ::set-env name=JFROG_CLI_BUILD_NUMBER::$(echo $GITHUB_RUN_NUMBER)
        echo ::set-env name=JFROG_CLI_BUILD_URL::$(echo $BUILD_URL)
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo $VERSION
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use 'sha' when on master tag convention
        [ "$VERSION" == "master" ] && VERSION=$(echo "${{ github.sha }}" | cut -c1-7)
        echo ::set-env name=IMG_VERSION::$(echo "sha-$VERSION")
