name: CI Build Testing
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: AWS CLI
      uses: ItsKarma/aws-cli@v1.70.0
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 549450938468.dkr.ecr.us-east-2.amazonaws.com
          aws lambda create-function --region us-east-2 --function-name my-function --package-type Image --code ImageUri=549450938468.dkr.ecr.us-east-2.amazonaws.com/myrepo:latest

