name: CI Build Testing
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: myrepo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    - name: Lambda trigger
      env:
        IMAGE: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      run: |
        aws lambda create-function --region us-east-2 --function-name my-function --package-type Image --code ImageUri=$IMAGE --role arn:aws:iam::549450938468:role/lambda_test
        aws lambda update-function-code --region us-east-2 --function-name my-function --image-uri $IMAGE
